services:
  nginx-rtmp:
    image: alfg/nginx-rtmp:latest
    # platform: linux/arm64
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8081:80" # para ver el panel de estad√≠sticas
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
